<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGCDtu2W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGCDtu2W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGCDtu2W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGCDtu2W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGCDtu2W\App_KernelDevDebugContainer([
    'container.build_hash' => 'GCDtu2W',
    'container.build_id' => '378a7a0b',
    'container.build_time' => 1736777511,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGCDtu2W');
